### ISSUE TITLE
Test Github integration

### ISSUE THREAD

**Issue by gbrian** [gbrian/repofunding#4]
_REMOVE.ME: Thanks for taking the time to open an issue, we will check and get back to you asp.
Please feel the sections below_

### Issue or new requests 
_REMOVE.ME: tell us about the issue or new request._

### How to reproduce
_REMOVE.ME: tell us how we can reproduce it._

### Guidelines
In case you are interested in solve this issue, please follow [CONTRIBUTING.MD](CONTRIBUTING.MD)

_@repofunding is helping on maintaing this repository. **Visit us to know more at www.repofunding.com**_

@repofunding test

**Comment by gbrian** [comment]
More testing @repofunding :)

**Comment by gbrian** [comment]
No news... @repofunding ?

**Comment by repofunding** [comment]
Error: 403 error making request POST https://api.github.com/repos/gbrian/repofunding/issues/4/comments: "Forbidden" 😔

**Comment by gbrian** [comment]
Dammit, @repofunding

**Comment by gbrian** [comment]
@repounding my friend!

**Comment by repofunding** [comment]
Hi :wave:!

**Comment by repofunding** [comment]
Hi :wave:!

**Comment by repofunding** [comment]
Hi :wave:!

**Comment by repofunding** [comment]
Hi :wave:!

**Comment by gbrian** [comment]
@repofunding say hello!

**Comment by repofunding** [comment]
Hi :wave:!

**Comment by gbrian** [comment]
@repofunding delete your comments

**Comment by repofunding** [comment]
Hi :wave:!

**Comment by gbrian** [comment]
@repofunding delete your comments

**Comment by gbrian** [comment]
@repofunding dammit, delete your comments

**Comment by gbrian** [comment]
@repofunding what if they are multiple references? delete your comments

**Comment by repofunding** [comment]
Waiting for reactions!

**Comment by gbrian** [comment]
@repofunding rules!

**Comment by gbrian** [comment]
@repofunding yeh,

**Comment by gbrian** [comment]
@repofunding notif

**Comment by repofunding** [comment]
### Supporting by 1$
 Support this issue with [![Support this asset](https://img.shields.io/badge/support-$1-lightgray.svg)](http://google.com.au/)  by reacting to this comment with 👍

**Comment by repofunding** [comment]
### Supporting by 5$ by reacting to this comment with 👍 
### Supporters : [![Support this asset](https://img.shields.io/badge/vijai-$5-green.svg)](http://google.com.au/) [![Support this asset](https://img.shields.io/badge/user2-$5-green.svg)](http://google.com.au/)

**Comment by gbrian** [comment]
@repofunding support 884875757

**Comment by gbrian** [comment]
@repofunding how's going?

**Comment by gbrian** [comment]
@repofunding delete your comments

**Comment by repofunding** [comment]
Ops, did I not get your Paypal.Me id.
Please post: `@repofunding support paypalme_id`
